[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npx prisma db push"

[deploy]
startCommand = "npm run indexer"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
