[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate"

[deploy]
startCommand = "npx prisma db push && npm run reset-db && npm run indexer"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
